#!/usr/bin/env python
"""Generate full sklearn classification_report metrics (per-class P/R/F1/support +
macro, micro, weighted, balanced accuracy) for every prediction file under
outputs/predictions/.

**Primary analytical metric**: Macro F1 (every class counts equally — honest on
imbalanced classes where micro/weighted are dominated by majority-class bias).
**Secondary**: accuracy / micro F1 (they are equal in single-label classification
— reported for completeness, but do not use for ranking).
**Also reported**: weighted F1, balanced accuracy, per-class P/R/F1/support.

Writes:
- outputs/reports/detailed_classification.json — full structured dict
- outputs/reports/detailed_classification.md — human-readable grouped tables

Usage:
    $UV_RUN python scripts/detailed_classification_report.py
    $UV_RUN python scripts/detailed_classification_report.py --filter roberta_mlp
"""
import argparse
import json
from collections import defaultdict
from pathlib import Path

from sklearn.metrics import (accuracy_score, balanced_accuracy_score,
                             classification_report, f1_score, precision_score,
                             recall_score)


def load_predictions(path: Path) -> tuple[list[str], list[str]]:
    rs = [json.loads(l) for l in open(path)]
    y_true = [r.get("gold_label", "") for r in rs]
    y_pred = [r.get("predicted_label", "") for r in rs]
    valid = [(t, p) for t, p in zip(y_true, y_pred) if t and p]
    if not valid:
        return [], []
    yt, yp = zip(*valid)
    return list(yt), list(yp)


def extract_dataset_task(stem: str) -> tuple[str, str, str]:
    """Parse <model>_<dataset>_<task> from file stem. Handles hyphenated model names."""
    # Known datasets
    datasets = ["mbti", "essays", "pandora", "personality_evd"]
    for ds in datasets:
        marker = f"_{ds}_"
        if marker in stem:
            model, rest = stem.split(marker, 1)
            return model, ds, rest
    # Fallback — split on last two underscores
    parts = stem.rsplit("_", 2)
    if len(parts) == 3:
        return parts[0], parts[1], parts[2]
    return stem, "unknown", "unknown"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--predictions_dir", default="outputs/predictions/")
    parser.add_argument("--output_dir", default="outputs/reports/")
    parser.add_argument("--filter", help="Substring to filter file stems")
    args = parser.parse_args()

    pred_dir = Path(args.predictions_dir)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    structured: dict[str, dict] = {}
    for pf in sorted(pred_dir.glob("*.jsonl")):
        if args.filter and args.filter not in pf.stem:
            continue
        yt, yp = load_predictions(pf)
        if not yt:
            continue
        report_dict = classification_report(yt, yp, zero_division=0, output_dict=True)
        # Compute all averaging variants explicitly — paper-ready metric set
        structured[pf.stem] = {
            "n_samples": len(yt),
            # Primary (for decision-making):
            "f1_macro": float(f1_score(yt, yp, average="macro", zero_division=0)),
            # Secondary (descriptive):
            "accuracy": float(accuracy_score(yt, yp)),
            "f1_micro": float(f1_score(yt, yp, average="micro", zero_division=0)),
            "f1_weighted": float(f1_score(yt, yp, average="weighted", zero_division=0)),
            "balanced_accuracy": float(balanced_accuracy_score(yt, yp)),
            "precision_macro": float(precision_score(yt, yp, average="macro", zero_division=0)),
            "precision_micro": float(precision_score(yt, yp, average="micro", zero_division=0)),
            "precision_weighted": float(precision_score(yt, yp, average="weighted", zero_division=0)),
            "recall_macro": float(recall_score(yt, yp, average="macro", zero_division=0)),
            "recall_micro": float(recall_score(yt, yp, average="micro", zero_division=0)),
            "recall_weighted": float(recall_score(yt, yp, average="weighted", zero_division=0)),
            # Full per-class + averages for drill-down (same structure as before):
            "report": report_dict,
        }

    (out_dir / "detailed_classification.json").write_text(
        json.dumps(structured, indent=2, default=str)
    )
    print(f"Wrote {len(structured)} reports to {out_dir}/detailed_classification.json")

    # Build human-readable markdown grouped by (dataset, task) → one table per task,
    # rows = models, columns = per-class metrics + macro/weighted avg.
    by_group: dict[tuple[str, str], list[tuple[str, dict]]] = defaultdict(list)
    for stem, entry in structured.items():
        model, dataset, task = extract_dataset_task(stem)
        by_group[(dataset, task)].append((model, entry))

    md_lines = [
        "# Detailed Classification Reports — All Averaging Variants",
        "",
        "Generated by `scripts/detailed_classification_report.py` via sklearn.",
        "",
        "### How to read these tables",
        "",
        "We report **all** standard averaging variants for transparency, but you should ",
        "**use Macro F1 to compare models and make decisions**. Rationale:",
        "",
        "- **Macro F1** (`f1_macro`) — **PRIMARY**. Arithmetic mean of per-class F1. ",
        "  Each class counts equally. Honest on imbalanced data.",
        "- **Accuracy** / **Micro F1** (`f1_micro`) — Mathematically equal to accuracy for ",
        "  single-label classification. Inflated by majority class on imbalanced tasks.",
        "- **Weighted F1** (`f1_weighted`) — F1 averaged weighted by class support. ",
        "  Dominated by majority class → same bias as accuracy. Do not use for ranking.",
        "- **Balanced Accuracy** (`bal_acc`) — Mean recall per class. Intuitive twin of ",
        "  Macro F1 when you care about catching every class equally.",
        "- **Per-class P / R / F1 / support** — Drill-down for failure analysis (e.g., ",
        "  detecting majority-class collapse where a class has recall ≈ 0).",
        "",
        "> **Decision rule**: when two models' accuracies differ by < 5 pp but macro F1 ",
        "> differs by > 3 pp, trust macro F1.",
        "",
        "---",
        "",
    ]

    for (dataset, task), rows in sorted(by_group.items()):
        md_lines.append(f"## {dataset} — {task}")
        md_lines.append("")

        # Collect all class labels across models for this task
        all_labels: set[str] = set()
        for _, entry in rows:
            for k in entry["report"]:
                if k not in ("accuracy", "macro avg", "weighted avg"):
                    all_labels.add(k)
        sorted_labels = sorted(all_labels)

        # ---- Summary table (averaging variants) ---------------------------
        md_lines.append("### Summary — averaging variants (sorted by Macro F1, desc)")
        md_lines.append("")
        header_s = ["Model", "N", "Accuracy", "Micro F1", "Macro F1 ⭐", "Weighted F1", "Bal Acc", "Macro P", "Macro R"]
        md_lines.append("| " + " | ".join(header_s) + " |")
        md_lines.append("|" + "|".join(["---"] * len(header_s)) + "|")
        sorted_rows = sorted(rows, key=lambda r: -r[1]["f1_macro"])
        for model, entry in sorted_rows:
            md_lines.append("| " + " | ".join([
                model,
                str(entry["n_samples"]),
                f"{entry['accuracy']:.3f}",
                f"{entry['f1_micro']:.3f}",
                f"**{entry['f1_macro']:.3f}**",
                f"{entry['f1_weighted']:.3f}",
                f"{entry['balanced_accuracy']:.3f}",
                f"{entry['precision_macro']:.3f}",
                f"{entry['recall_macro']:.3f}",
            ]) + " |")
        md_lines.append("")

        # ---- Drill-down table (per-class) ---------------------------------
        md_lines.append("### Per-class drill-down (precision / recall / F1 / support)")
        md_lines.append("")
        header = ["Model"]
        for lab in sorted_labels:
            header += [f"{lab} P", f"{lab} R", f"{lab} F1", f"{lab} n"]
        md_lines.append("| " + " | ".join(header) + " |")
        md_lines.append("|" + "|".join(["---"] * len(header)) + "|")
        for model, entry in sorted_rows:
            rep = entry["report"]
            row = [model]
            for lab in sorted_labels:
                cls = rep.get(lab, {})
                row += [
                    f"{cls.get('precision', 0):.3f}",
                    f"{cls.get('recall', 0):.3f}",
                    f"{cls.get('f1-score', 0):.3f}",
                    f"{int(cls.get('support', 0))}",
                ]
            md_lines.append("| " + " | ".join(row) + " |")
        md_lines.append("")
        md_lines.append("---")
        md_lines.append("")

    (out_dir / "detailed_classification.md").write_text("\n".join(md_lines))
    print(f"Wrote markdown report to {out_dir}/detailed_classification.md")


if __name__ == "__main__":
    main()
