#!/usr/bin/env python
"""Generate full sklearn classification_report (per-class precision/recall/F1/support,
macro avg, weighted avg) for every prediction file under outputs/predictions/.

Writes outputs/reports/detailed_classification.json with the structured dict form
(output_dict=True), and a human-readable outputs/reports/detailed_classification.md
with per-task tables grouped by model.

Usage:
    $UV_RUN python scripts/detailed_classification_report.py
    $UV_RUN python scripts/detailed_classification_report.py --filter roberta_mlp
"""
import argparse
import json
from collections import defaultdict
from pathlib import Path

from sklearn.metrics import classification_report


def load_predictions(path: Path) -> tuple[list[str], list[str]]:
    rs = [json.loads(l) for l in open(path)]
    y_true = [r.get("gold_label", "") for r in rs]
    y_pred = [r.get("predicted_label", "") for r in rs]
    valid = [(t, p) for t, p in zip(y_true, y_pred) if t and p]
    if not valid:
        return [], []
    yt, yp = zip(*valid)
    return list(yt), list(yp)


def extract_dataset_task(stem: str) -> tuple[str, str, str]:
    """Parse <model>_<dataset>_<task> from file stem. Handles hyphenated model names."""
    # Known datasets
    datasets = ["mbti", "essays", "pandora", "personality_evd", "pandora_big5"]
    for ds in datasets:
        marker = f"_{ds}_"
        if marker in stem:
            model, rest = stem.split(marker, 1)
            return model, ds, rest
    # Fallback — split on last two underscores
    parts = stem.rsplit("_", 2)
    if len(parts) == 3:
        return parts[0], parts[1], parts[2]
    return stem, "unknown", "unknown"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--predictions_dir", default="outputs/predictions/")
    parser.add_argument("--output_dir", default="outputs/reports/")
    parser.add_argument("--filter", help="Substring to filter file stems")
    args = parser.parse_args()

    pred_dir = Path(args.predictions_dir)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    structured: dict[str, dict] = {}
    for pf in sorted(pred_dir.glob("*.jsonl")):
        if args.filter and args.filter not in pf.stem:
            continue
        yt, yp = load_predictions(pf)
        if not yt:
            continue
        report_dict = classification_report(yt, yp, zero_division=0, output_dict=True)
        structured[pf.stem] = {
            "n_samples": len(yt),
            "report": report_dict,
        }

    (out_dir / "detailed_classification.json").write_text(
        json.dumps(structured, indent=2, default=str)
    )
    print(f"Wrote {len(structured)} reports to {out_dir}/detailed_classification.json")

    # Build human-readable markdown grouped by (dataset, task) → one table per task,
    # rows = models, columns = per-class metrics + macro/weighted avg.
    by_group: dict[tuple[str, str], list[tuple[str, dict]]] = defaultdict(list)
    for stem, entry in structured.items():
        model, dataset, task = extract_dataset_task(stem)
        by_group[(dataset, task)].append((model, entry))

    md_lines = [
        "# Detailed Classification Reports",
        "",
        "Per-class precision/recall/F1/support + macro and weighted averages.",
        "Generated by `scripts/detailed_classification_report.py` via",
        "`sklearn.metrics.classification_report(output_dict=True)`.",
        "",
        "---",
        "",
    ]

    for (dataset, task), rows in sorted(by_group.items()):
        md_lines.append(f"## {dataset} — {task}")
        md_lines.append("")

        # Collect all class labels across models for this task
        all_labels: set[str] = set()
        for _, entry in rows:
            for k in entry["report"]:
                if k not in ("accuracy", "macro avg", "weighted avg"):
                    all_labels.add(k)
        sorted_labels = sorted(all_labels)

        # Header
        header = ["Model", "N", "Accuracy"]
        for lab in sorted_labels:
            header += [f"{lab} P", f"{lab} R", f"{lab} F1", f"{lab} n"]
        header += ["Macro P", "Macro R", "Macro F1", "Weighted P", "Weighted R", "Weighted F1"]
        md_lines.append("| " + " | ".join(header) + " |")
        md_lines.append("|" + "|".join(["---"] * len(header)) + "|")

        for model, entry in sorted(rows):
            rep = entry["report"]
            n = entry["n_samples"]
            acc = rep.get("accuracy", 0.0)
            row = [model, str(n), f"{acc:.3f}"]
            for lab in sorted_labels:
                cls = rep.get(lab, {})
                row += [
                    f"{cls.get('precision', 0):.3f}",
                    f"{cls.get('recall', 0):.3f}",
                    f"{cls.get('f1-score', 0):.3f}",
                    f"{int(cls.get('support', 0))}",
                ]
            mac = rep.get("macro avg", {})
            wei = rep.get("weighted avg", {})
            row += [
                f"{mac.get('precision', 0):.3f}",
                f"{mac.get('recall', 0):.3f}",
                f"{mac.get('f1-score', 0):.3f}",
                f"{wei.get('precision', 0):.3f}",
                f"{wei.get('recall', 0):.3f}",
                f"{wei.get('f1-score', 0):.3f}",
            ]
            md_lines.append("| " + " | ".join(row) + " |")
        md_lines.append("")
        md_lines.append("---")
        md_lines.append("")

    (out_dir / "detailed_classification.md").write_text("\n".join(md_lines))
    print(f"Wrote markdown report to {out_dir}/detailed_classification.md")


if __name__ == "__main__":
    main()
